[package]
name = "nu-v"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1"
petgraph = "0.7"
color-eyre = "0.6"
colog = "1.3.0"
log = "0.4"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
test-log = { version = "0.2.17", features = ["log"] }
